name = "cloudflare-wrangler"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-08"


[site]
bucket = "./dist"
entry-point = "workers-site"
